exports.anchorman = [
  "I immediately regret this decision."
  , "I’ll have a Manhattan. And kick the vermouth to the side with a pair of steel-toed boots."
  , "Oh, I can barely lift my right arm ’cause I did so many. I don’t know if you heard me counting. I did over a thousand."
  , "Baxter, is that you? Baxter! Bark twice if you’re in Milwaukee."
  , "The human torch was denied a bank loan."
  , "It is anchorman, not anchorlady. And that is a scientific fact."
  , "I’m in a glass case of emotion!"
  , "Don’t act like you’re not impressed."
  , "I would like to extend to you an invitation to the pants party."
  , "I love lamp."
  , "You know I don’t speak Spanish."
  , "They’ve done studies, you know. 60 percent of the time, it works every time."
];

exports.startrek = [
  "The bureaucratic mentality is the only constant in the universe."
  , "It can be argued that a human is ultimately the sum of his experiences."
  , "How we deal with death is at least as important as how we deal with life."
  , "Money is money, but women...are better."
  , "Fate: protects fools, little children, and ships named Enterprise."
  , "Rumors of my assimilation are greatly exaggerated."
  , "What we leave behind is not as important as how we've lived."
  , "Being first at any cost is not always the point."
  , "Those who clothe themselves in good deeds are well-camouflaged."
  , "The first time any man's freedom is trodden on, we're all damaged."
  , "You may test that assumption at your convenience."
  , "Time is a companion that goes with us on a journey. It reminds us to cherish each moment, because it will never come again."
  , "Assimilate this!"
  , "Believing oneself to be perfect is often the sign of a delusional mind."
  , "The truth is usually just an excuse for a lack of imagination."
  , "If there's nothing wrong with me...maybe there's something wrong with the universe!"
  , "Curious how often you humans manage to obtain that which you do not want."
  , "Human bonding rituals often involve a great deal of talking, and dancing, and crying."
  , "I would be delighted to offer any advice I can on understanding women. When I have some, I’ll let you know."
  , "Please, Captain, not in front of the Klingons."
  , "It is possible to commit no errors and still lose. That is not a weakness. That is life."
  , "I changed the conditions of the test. I don’t like to lose."
  , "Do you know the old Klingon proverb that revenge is a dish best served cold? It is very cold — in space."
  , "Lieutenant, you are looking at the only man to beat the no-win scenario."
  , "Well, once again, we’ve saved civilization as we know it. And the good news is, they’re not going to prosecute."
  , "For everything, there is a first time."
  , "Space… the final frontier."
  , "Live long, and prosper."
  , "Let them eat static."
  , "For that one fraction of a second, you were open to options you had never considered. *That* is the exploration that awaits you."
  // Borg
  , "Resistance is futile"
  , "You will be assimilated"
  // Data
  , "Given Commander Riker's affection for archaic musical forms, I have elected to present the following in honor of their conjugation."
  // Picard
  , "As for my crew, it may be healthy to shake up the status quo occasionally."
  , "Dr. Soong's penchant for whimsical names seems to have no end."
  , "For humans, touch can connect you to an object in a very personal way, make it seem more real."
  , "Mr. Data, lay in a course for the 24th century. I suspect our future is there waiting for us."
  // Crusher
  , "Next, our hands and feet will get cold, then numb, and some of the capillaries on the exposed sections of the skin may burst."
  // Riker
  , "Photon torpedo. Isn't that the universal greeting when communications are down?"
  , "I think you've let your personal feelings cloud your judgement."
  , "Gentlemen, we're giving you an assignment. The one thing we don't want to hear is that it's impossible."
  , "You're incapable of that level of incompetence, Mr. La Forge!"
  // La Forge
  , "Part of what we do is learn more about other species."
  , "But I say forget the numbers! There's no way the computer can compensate for the human factor, the, the intuition, the experience."
  , "Matter-antimatter mixture ratio settings... at optimum balance. Reaction sequence... corresponding to specified norms. Magnetic plasma transfer to warp field generators per program specs. Commander, we should be going like a bat out of hell!"
  , "You know, I've always thought that technology could solve almost any problem. It enhances the quality of our lives, lets us travel across the galaxy - even gave me my vision. But sometimes, you just have to turn it all off."
  , "Just because something's old doesn't mean you throw it away."
  , "A good engineer is always a wee bit conservative, at least on paper."
  , "I may be captain by rank; but I never wanted to be anything else but an engineer."
  , "Sometimes I feel more comfortable with engine schematics than people."
  , "You know, there's nothing wrong with a healthy fantasy life, as long as you don't let it take over."
  , "Inertial dampers failing. We're losing attitude control."
  , "Well, maybe necessity really is the mother of invention."
  , "Sure goes against everything we've always heard about not polluting the timeline, doesn't it?"
  , "Captain, we've got a problem with the warp core, or the phase inducers - or some other damn thing."
  , "Wesley, you may get straight A's in school, but there's a lot you need to learn about poker."
  , "Children are a lot stronger than you think. As long as they know you love them, they can handle just about anything life throws at 'em, you know."
  , "This is gonna be like puttin' together a big jigsaw puzzle when you don't even know what the picture's supposed to be."
  , "I never lie when I've got sand in my shoes, Commodore."
];